apiVersion: mocks.microcks.io/v1alpha1
kind: APIExamples
metadata:
  name: FINOS TraderX Position Service
  version: 0.1.0
operations:
  GET /trades/{accountId}:
    '52355':
      request:
        parameters:
          accountId: 52355
      response:
        mediaType: application/json
        body:
          - id: TRADE-52355-AABBCC
            accountId: 52355
            security: BAC
            side: Sell
            state: Settled
            quantity: 2400
            updated: 2026-03-11T08:57:54.758+00:00
            created: 2026-03-11T08:57:54.758+00:00
  GET /positions/{accountId}:
    '52355':
      request:
        parameters:
          accountId: 52355
      response:
        mediaType: application/json
        body:
          - accountId: 52355
            security: BAC
            quantity: -2400
            updated: 2026-03-11T08:57:54.763+00:00  

